imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
        strict_requirements: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user1: { password: user123, roles: ROLE_USER }

    firewalls:
        main:
            http_basic: ~
